"""
VENGAM Auditor — Economy, AntiCheat & Config Patterns
"""
from __future__ import annotations

ECONOMY_PATTERNS: list[dict] = [
    {
        "title": "In-App Purchase Receipt Validation Disabled",
        "regex": r"(?i)(skip[_\-]?receipt[_\-]?validation|bypass[_\-]?iap|receipt[_\-]?check\s*=\s*(false|0|disabled)|verifyReceipt\s*=\s*false)",
        "severity": "CRITICAL", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "IAP Bypass",
        "description": "IAP receipt validation is disabled. Enables fake purchases without payment.",
        "simulation": "Attacker submits fake receipt. Server grants premium content unconditionally.",
        "score_value": 40,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
        "cwe_id": "CWE-345", "owasp_ref": "M5: Insufficient Cryptography", "category": "Economy",
        "triage_note": "All receipt validation MUST be server-side against Google Play or Apple receipt API.",
    },
    {
        "title": "Client-Side Currency / Score Validation",
        "regex": r"(?i)(client[_\-]?side[_\-]?(score|currency|gold|coins|gems|balance)|localScore|localBalance|clientValidat)",
        "severity": "HIGH", "confidence": "MEDIUM", "exploitability": "LIKELY",
        "secret_type": "Client-Side Trust",
        "description": "Game economy values appear to be validated client-side — a fundamental game security flaw.",
        "simulation": "Attacker uses memory editor to set currency to MAX_INT. Server accepts the value.",
        "score_value": 25,
        "cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
        "cwe_id": "CWE-602", "owasp_ref": "M1: Improper Platform Usage", "category": "Economy",
        "triage_note": "Verify file is game-specific (not address validation library). Economy must be server-authoritative.",
    },
    {
        "title": "Leaderboard Score Submission Without Auth",
        "regex": r"(?i)(submit[_\-]?score|post[_\-]?score|leaderboard[_\-]?submit)\s*\([^)]{0,60}(unsigned|no[_\-]?auth|unauthenticated)",
        "severity": "MEDIUM", "confidence": "MEDIUM", "exploitability": "LIKELY",
        "secret_type": "Leaderboard Integrity",
        "description": "Score submission lacks authentication or signing, enabling arbitrary score injection.",
        "simulation": "Attacker crafts a score submission with arbitrary values to top the leaderboard.",
        "score_value": 15,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
        "cwe_id": "CWE-345", "owasp_ref": "M1: Improper Platform Usage", "category": "Economy",
        "triage_note": "Sign all score submissions with HMAC using a session-bound key.",
    },
    {
        "title": "PlayFab Secret Key",
        "regex": r"(?i)playfab[_\-]?(secret[_\-]?key|developer[_\-]?secret|title[_\-]?secret)\s*[=:]\s*['\"]([A-Z0-9]{20,})['\"]",
        "severity": "CRITICAL", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Game Backend Credential",
        "description": "PlayFab developer secret key grants admin-level access: player data, inventory, economy.",
        "simulation": "Attacker calls PlayFab Admin API to grant unlimited currency or export all player data.",
        "score_value": 35,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "Economy",
        "triage_note": "Rotate at developer.playfab.com immediately. Key must NEVER be in the client.",
    },
    {
        "title": "GameSparks / Nakama / LootLocker Backend Key",
        "regex": r"(?i)(gamesparks[_\-]?(api[_\-]?key|secret)|nakama[_\-]?server[_\-]?key|lootlocker[_\-]?(api[_\-]?key|game[_\-]?key))\s*[=:]\s*['\"]([a-zA-Z0-9\-_]{16,})['\"]",
        "severity": "CRITICAL", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Game Backend Credential",
        "description": "Game backend key (GameSparks/Nakama/LootLocker) found. Manages player accounts and economy.",
        "simulation": "Attacker accesses admin API to manipulate player economies and extract all player PII.",
        "score_value": 35,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "Economy",
        "triage_note": "Server keys must never be client-side. Rotate immediately.",
    },
    {
        "title": "Braincloud App Secret",
        "regex": r"(?i)(braincloud[_\-]?(secret|app[_\-]?secret|server[_\-]?secret))\s*[=:]\s*['\"]([a-zA-Z0-9\-_]{20,})['\"]",
        "severity": "CRITICAL", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Game Backend Credential",
        "description": "Braincloud app secret grants full admin access to player data, leaderboards, and economy.",
        "simulation": "Attacker calls Braincloud admin API to modify player currency or execute cloud code.",
        "score_value": 35,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "Economy",
        "triage_note": "Rotate at portal.braincloudservers.com. Only app ID (not secret) should be in client.",
    },
]

ANTICHEAT_PATTERNS: list[dict] = [
    {
        "title": "Anti-Cheat Bypass String Detected",
        "regex": r"(?i)(disable[_\-]?anticheat|bypass[_\-]?(eac|be|vac|xigncode|gameguard)|anticheat[_\-]?disabled|cheat[_\-]?engine[_\-]?whitelist)",
        "severity": "CRITICAL", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Anti-Cheat Bypass",
        "description": "String indicating anti-cheat bypass logic found. Critical indicator of debug/test build.",
        "simulation": "Attacker uses bypass string to run game in unprotected state, enabling wallhacks/aimbots.",
        "score_value": 40,
        "cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:N",
        "cwe_id": "CWE-693", "owasp_ref": "M10: Extraneous Functionality", "category": "AntiCheat",
        "triage_note": "Strip all bypass strings via ProGuard rules. Check if this is a test build accidentally shipped.",
    },
    {
        "title": "Debug / God Mode Flag",
        "regex": r"(?i)(god[_\-]?mode|debug[_\-]?mode|invincible|no[_\-]?clip|infinite[_\-]?(ammo|health|money|gold|gems)|unlock[_\-]?all)",
        "severity": "HIGH", "confidence": "MEDIUM", "exploitability": "LIKELY",
        "secret_type": "Debug Flag",
        "description": "Debug gameplay flags (god mode, infinite resources) found. May be activatable at runtime.",
        "simulation": "Attacker locates the memory address and toggles the flag for unfair advantage.",
        "score_value": 20,
        "cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
        "cwe_id": "CWE-489", "owasp_ref": "M10: Extraneous Functionality", "category": "AntiCheat",
        "triage_note": "Verify file is game-specific (not a third-party debug library). Remove before release.",
    },
    {
        "title": "Root / Emulator Detection Bypass",
        "regex": r"(?i)(skip[_\-]?root[_\-]?check|bypass[_\-]?(root|emulator)[_\-]?detection|rootcheck[_\-]?disabled|isRooted\s*=\s*(false|0))",
        "severity": "HIGH", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Security Check Bypass",
        "description": "Root or emulator detection disabled. Allows running on rooted device with Frida/memory editing.",
        "simulation": "Attacker sets bypass flag and runs Frida on rooted device to hook game logic.",
        "score_value": 25,
        "cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:M/I:H/A:N",
        "cwe_id": "CWE-693", "owasp_ref": "M8: Code Tampering", "category": "AntiCheat",
        "triage_note": "Ensure this is not debug-only code. Use Play Integrity API for robust attestation.",
    },
    {
        "title": "SSL Certificate Pinning Disabled",
        "regex": r"(?i)(ssl[_\-]?pinning[_\-]?(disabled|off|false|bypass)|disable[_\-]?ssl[_\-]?pin|certificate[_\-]?pinning\s*=\s*(false|0|disabled))",
        "severity": "HIGH", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "TLS Security Disabled",
        "description": "SSL/TLS certificate pinning explicitly disabled. Allows MITM attacks on API traffic.",
        "simulation": "Attacker intercepts HTTPS with Burp Suite, reads all API calls, modifies responses.",
        "score_value": 25,
        "cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "cwe_id": "CWE-295", "owasp_ref": "M3: Insecure Communication", "category": "AntiCheat",
        "triage_note": "Re-enable pinning. Use OkHttp CertificatePinner or network_security_config with pin-set.",
    },
]

CONFIG_PATTERNS: list[dict] = [
    {
        "title": "network_security_config: cleartext or trust-all",
        "regex": r"(?i)(cleartextTrafficPermitted\s*=\s*['\"]?true['\"]?|<trust-anchors>[\s\S]{0,200}<certificates\s+src=['\"]user['\"])",
        "severity": "MEDIUM", "confidence": "HIGH", "exploitability": "LIKELY",
        "secret_type": "Network Security Misconfiguration",
        "description": "Network security config permits cleartext traffic or trusts user-installed CA certificates.",
        "simulation": "Attacker installs own CA cert and proxies all HTTPS traffic, bypassing pinning.",
        "score_value": 15,
        "cvss_vector": "CVSS:3.1/AV:A/AC:H/PR:N/UI:N/S:U/C:H/I:M/A:N",
        "cwe_id": "CWE-319", "owasp_ref": "M3: Insecure Communication", "category": "Config",
        "triage_note": "Remove cleartextTrafficPermitted=true and user CA trust anchors from production config.",
    },
    {
        "title": "android:allowBackup=true (Data Leakage Risk)",
        "regex": r'android:allowBackup\s*=\s*["\']true["\']',
        "severity": "LOW", "confidence": "HIGH", "exploitability": "THEORETICAL",
        "secret_type": "Android Manifest Misconfiguration",
        "description": "android:allowBackup=true allows ADB backup of private data, leaking tokens and credentials.",
        "simulation": "Attacker runs 'adb backup com.game.app' to extract game save data and cached credentials.",
        "score_value": 5,
        "cvss_vector": "CVSS:3.1/AV:P/AC:L/PR:N/UI:N/S:U/C:M/I:N/A:N",
        "cwe_id": "CWE-530", "owasp_ref": "M2: Insecure Data Storage", "category": "Config",
        "triage_note": "Set android:allowBackup=false in AndroidManifest.xml unless backup is a deliberate feature.",
    },
    {
        "title": "Exported Component Without Permission",
        "regex": r'android:exported\s*=\s*["\']true["\'](?![\s\S]{0,200}android:permission)',
        "severity": "MEDIUM", "confidence": "MEDIUM", "exploitability": "LIKELY",
        "secret_type": "Android Manifest Misconfiguration",
        "description": "Activity/Service/Provider exported without a permission guard. Other apps can invoke it directly.",
        "simulation": "Attacker app invokes the exported component with crafted Intent to access game data.",
        "score_value": 10,
        "cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:M/I:M/A:N",
        "cwe_id": "CWE-926", "owasp_ref": "M1: Improper Platform Usage", "category": "Config",
        "triage_note": "Add android:permission or set android:exported=false for internal components.",
    },
]
