"""
VENGAM Auditor — Game Engine Patterns
Unity, Unreal, Photon, Cocos, GameAnalytics.
"""
from __future__ import annotations

GAME_ENGINE_PATTERNS: list[dict] = [
    {
        "title": "Unity Cloud Build API Key",
        "regex": r"(?i)unity[_\-\s]?(cloud[_\-\s]?build|ucb)[_\-\s]?(api[_\-\s]?key|token|secret)[^a-zA-Z0-9]([a-zA-Z0-9]{20,})",
        "severity": "HIGH", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Unity Cloud Credential",
        "description": "Unity Cloud Build API key. Enables triggering builds and downloading build artifacts.",
        "simulation": "Attacker triggers rogue builds or injects malicious code into build pipelines.",
        "score_value": 25,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:N",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "GameEngine",
        "triage_note": "Rotate at cloud.unity.com. Use CI/CD secrets manager.",
    },
    {
        "title": "Unity Analytics / UGS Secret Key",
        "regex": r"(?i)(unity[_\-]?(analytics|gaming[_\-]services|ugs)[_\-]?(key|secret|token))\s*[=:]\s*['\"]([a-zA-Z0-9\-_]{20,})['\"]",
        "severity": "MEDIUM", "confidence": "HIGH", "exploitability": "LIKELY",
        "secret_type": "Unity Analytics Credential",
        "description": "Unity Analytics or UGS key found. May allow manipulation of telemetry or remote config.",
        "simulation": "Attacker sends fake analytics events or reads remote config to reverse-engineer balance.",
        "score_value": 15,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:M/I:M/A:N",
        "cwe_id": "CWE-306", "owasp_ref": "M1: Improper Platform Usage", "category": "GameEngine",
        "triage_note": "Rotate at dashboard.unity3d.com/gaming/services.",
    },
    {
        "title": "IL2CPP Symbol Map Exposed",
        "regex": r"(il2cpp_codegen_initialize_runtime_metadata|IL2CPP_RUNTIME_CLASS_INIT|il2cpp_object_new)\s*\(",
        "severity": "MEDIUM", "confidence": "HIGH", "exploitability": "LIKELY",
        "secret_type": "Debug Symbol Leak",
        "description": "IL2CPP debug symbols present. Significantly accelerates reverse engineering of game logic.",
        "simulation": "Attacker uses symbol map with Ghidra/IDA to rapidly locate and hook game functions.",
        "score_value": 15,
        "cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:M/I:N/A:N",
        "cwe_id": "CWE-540", "owasp_ref": "M10: Extraneous Functionality", "category": "GameEngine",
        "triage_note": "Disable IL2CPP symbol generation in Unity Build Settings.",
    },
    {
        "title": "Unity Remote Config Endpoint Exposed",
        "regex": r"https?://config\.unity3d\.com/[a-zA-Z0-9/\-_?=&]+",
        "severity": "LOW", "confidence": "HIGH", "exploitability": "THEORETICAL",
        "secret_type": "Remote Config URL",
        "description": "Unity Remote Config endpoint exposed. May allow reading unpublished config or feature flags.",
        "simulation": "Attacker queries endpoint to read unreleased feature flags and game balance parameters.",
        "score_value": 5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
        "cwe_id": "CWE-200", "owasp_ref": "M2: Insecure Data Storage", "category": "GameEngine",
        "triage_note": "Ensure Remote Config rules require authentication.",
    },
    {
        "title": "Unreal Engine Encryption Key (AES-256)",
        "regex": r"(?i)(pak[_\-]?(encryption|aes)[_\-]?key|EncryptionKey)\s*[=:\"']+\s*([0-9A-Fa-f]{64})",
        "severity": "CRITICAL", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Asset Encryption Key",
        "description": "Unreal Engine PAK AES-256 encryption key found. Allows decryption of all game assets.",
        "simulation": "Attacker decrypts PAK files offline to extract anti-cheat logic and premium assets.",
        "score_value": 35,
        "cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "cwe_id": "CWE-321", "owasp_ref": "M9: Insecure Data Storage", "category": "GameEngine",
        "triage_note": "PAK keys must NEVER be in the client binary. Use server-side key provisioning.",
    },
    {
        "title": "Unreal Online Subsystem (EOS) Credentials",
        "regex": r"(?i)(EOS_ProductId|EOS_SandboxId|EOS_DeploymentId|EOS_ClientId|EOS_ClientSecret)\s*[=:]\s*['\"]([a-zA-Z0-9\-]{20,})['\"]",
        "severity": "HIGH", "confidence": "HIGH", "exploitability": "LIKELY",
        "secret_type": "Epic Online Services Credential",
        "description": "EOS credentials found. EOS_ClientSecret enables impersonating the game client.",
        "simulation": "Attacker impersonates the game client, manipulates leaderboards or queries player data.",
        "score_value": 20,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "GameEngine",
        "triage_note": "EOS_ClientSecret is server-only. EOS_ClientId alone is acceptable in client.",
    },
    {
        "title": "Photon App ID / Secret",
        "regex": r"(?i)(photon[_\-]?(app[_\-]?id|secret|realtime[_\-]?app[_\-]?id))\s*[=:]\s*['\"]([a-zA-Z0-9\-]{20,})['\"]",
        "severity": "HIGH", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Multiplayer Infrastructure Credential",
        "description": "Photon App ID or Secret found. Enables joining private game rooms and intercepting game messages.",
        "simulation": "Attacker connects to Photon servers, joins private lobbies, eavesdrops on game state sync.",
        "score_value": 20,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:M",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "GameEngine",
        "triage_note": "Rotate at dashboard.photonengine.com. Enforce custom authentication on rooms.",
    },
    {
        "title": "GameAnalytics Secret Key",
        "regex": r"(?i)(gameanalytics[_\-]?(secret[_\-]?key|game[_\-]?key))\s*[=:]\s*['\"]([a-zA-Z0-9]{40})['\"]",
        "severity": "MEDIUM", "confidence": "HIGH", "exploitability": "LIKELY",
        "secret_type": "Analytics Credential",
        "description": "GameAnalytics secret key found. Enables sending fraudulent analytics events.",
        "simulation": "Attacker floods endpoint with fake events to skew A/B test and monetisation metrics.",
        "score_value": 10,
        "cvss_vector": "CVSS:3.1/AV:N/AC:M/PR:N/UI:N/S:U/C:M/I:M/A:N",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "GameEngine",
        "triage_note": "Rotate at gameanalytics.com.",
    },
]
