"""
VENGAM Auditor — General Secret Patterns
Cloud credentials, auth tokens, communication keys, crypto.
"""
from __future__ import annotations

GENERAL_PATTERNS: list[dict] = [
    {
        "title": "Google / Firebase API Key",
        "regex": r"AIza[0-9A-Za-z\-_]{35}",
        "severity": "CRITICAL", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Cloud API Key",
        "description": "A Google/Firebase API key embedded in the binary may grant access to Firebase RTDB, Cloud Storage, or GCP services based on IAM permissions.",
        "simulation": "Attacker calls Firebase REST API to attempt unauthenticated read/write on the database.",
        "score_value": 30,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "General",
        "triage_note": "Verify Firebase security rules — key alone may not grant write access if rules require auth.",
    },
    {
        "title": "AWS Access Key ID",
        "regex": r"AKIA[0-9A-Z]{16}",
        "severity": "CRITICAL", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Cloud Credential",
        "description": "An AWS Access Key ID found in the APK enables programmatic access to AWS infrastructure when combined with its secret (often stored nearby).",
        "simulation": "Attacker configures AWS CLI, enumerates S3 buckets, and attempts IAM privilege escalation.",
        "score_value": 30,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "General",
        "triage_note": "Immediately search for paired AWS_SECRET_ACCESS_KEY nearby. Rotate via IAM console.",
    },
    {
        "title": "Stripe Secret Key",
        "regex": r"sk_live_[0-9a-zA-Z]{24,}",
        "severity": "CRITICAL", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Payment Credential",
        "description": "A live Stripe secret key enables creating charges, accessing customer PII, and initiating refunds/transfers.",
        "simulation": "Attacker enumerates customers, exports card metadata, initiates fraudulent refunds.",
        "score_value": 35,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        "cwe_id": "CWE-312", "owasp_ref": "M9: Insecure Data Storage", "category": "General",
        "triage_note": "Revoke immediately at dashboard.stripe.com/apikeys.",
    },
    {
        "title": "Stripe Publishable Key (Live)",
        "regex": r"pk_live_[0-9a-zA-Z]{24,}",
        "severity": "LOW", "confidence": "HIGH", "exploitability": "THEORETICAL",
        "secret_type": "Payment Key (Public)",
        "description": "Live Stripe publishable key confirms production environment.",
        "simulation": "Attacker confirms live environment and probes tokenization endpoint.",
        "score_value": 5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
        "cwe_id": "CWE-200", "owasp_ref": "M9: Insecure Data Storage", "category": "General",
        "triage_note": "Publishable keys are public by design. Risk is low unless paired with a secret key.",
    },
    {
        "title": "Slack Bot Token",
        "regex": r"xoxb-[0-9]{11}-[0-9]{11}-[a-zA-Z0-9]{24}",
        "severity": "HIGH", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Communication Token",
        "description": "Slack Bot token enables reading channel history, sending messages, and exfiltrating workspace member data.",
        "simulation": "Attacker enumerates private channels and extracts internal development communications.",
        "score_value": 20,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:M/A:N",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "General",
        "triage_note": "Revoke at api.slack.com/apps. Should never appear in a production APK.",
    },
    {
        "title": "SendGrid API Key",
        "regex": r"SG\.[a-zA-Z0-9_-]{22}\.[a-zA-Z0-9_-]{43}",
        "severity": "HIGH", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Email Service Credential",
        "description": "SendGrid key enables unauthorized bulk email, template access, and contact list exfiltration.",
        "simulation": "Attacker sends large-scale phishing via the legitimate account, bypassing spam filters.",
        "score_value": 20,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:M/I:H/A:N",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "General",
        "triage_note": "Revoke at app.sendgrid.com/settings/api_keys.",
    },
    {
        "title": "RSA / EC / SSH Private Key",
        "regex": r"-----BEGIN (RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----",
        "severity": "CRITICAL", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Cryptographic Private Key",
        "description": "A PEM private key can be used to impersonate the server, decrypt TLS traffic, or forge signed tokens.",
        "simulation": "Attacker uses the key for TLS interception or to forge signed JWTs/certificates.",
        "score_value": 40,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        "cwe_id": "CWE-321", "owasp_ref": "M10: Extraneous Functionality", "category": "General",
        "triage_note": "Revoke certificate, re-issue. Audit git history for when key was committed.",
    },
    {
        "title": "Hardcoded Password / Secret Assignment",
        "regex": r'(?i)(password|passwd|secret|api_secret|client_secret)\s*[=:]\s*[\'"]([^\'"]{8,})[\'"]',
        "severity": "HIGH", "confidence": "MEDIUM", "exploitability": "LIKELY",
        "secret_type": "Hardcoded Credential",
        "description": "A probable hardcoded password or secret found in key=value assignment. Manual review required.",
        "simulation": "Attacker extracts value and attempts credential stuffing against discovered auth endpoints.",
        "score_value": 20,
        "cvss_vector": "CVSS:3.1/AV:N/AC:M/PR:N/UI:N/S:U/C:H/I:M/A:N",
        "cwe_id": "CWE-259", "owasp_ref": "M9: Insecure Data Storage", "category": "General",
        "triage_note": "Manually verify value is not a placeholder (e.g. 'changeme', 'your_key_here').",
    },
    {
        "title": "JWT (Bearer Token)",
        "regex": r"eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}",
        "severity": "HIGH", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Authentication Token",
        "description": "Hardcoded JWT may allow direct authenticated access to backend APIs.",
        "simulation": "Attacker replays token against API routes; attempts alg=none privilege escalation.",
        "score_value": 25,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        "cwe_id": "CWE-798", "owasp_ref": "M3: Insecure Communication", "category": "General",
        "triage_note": "Decode at jwt.io to check expiry and claims. If not expired: treat as CRITICAL.",
    },
    {
        "title": "GitHub Personal Access Token",
        "regex": r"gh[pousr]_[A-Za-z0-9]{36,}",
        "severity": "CRITICAL", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Source Control Credential",
        "description": "GitHub PAT may allow read/write access to private source code repositories.",
        "simulation": "Attacker clones private repos, exfiltrates source code, may push malicious commits.",
        "score_value": 30,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:N",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "General",
        "triage_note": "Revoke at github.com/settings/tokens. Audit push events on affected repos.",
    },
    {
        "title": "Twilio Account SID + Auth Token",
        "regex": r"(?i)(twilio[^a-z0-9]|Twilio[A-Z]|TWILIO_)(account[_\-]?sid|auth[_\-]?token)\s*[=:]\s*['\"]?(AC[a-fA-F0-9]{32}|[a-fA-F0-9]{32})['\"]?",
        "severity": "HIGH", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Telephony Credential",
        "description": "Twilio Account SID or Auth Token with explicit Twilio context. Enables SMS/voice abuse.",
        "simulation": "Attacker sends bulk SMS or makes calls billed to the victim account.",
        "score_value": 20,
        "cvss_vector": "CVSS:3.1/AV:N/AC:M/PR:N/UI:N/S:U/C:M/I:H/A:N",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "General",
        "triage_note": "Verify not a Huawei AGC resource ID. Check twilio.com/console.",
    },
    {
        "title": "Agora App ID / Certificate",
        "regex": r"(?i)(agora[_\-]?(app[_\-]?id|certificate|token|app[_\-]?cert))\s*[=:]\s*['\"]([a-zA-Z0-9]{32})['\"]",
        "severity": "HIGH", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Real-Time Communication Credential",
        "description": "Agora App ID or Certificate found. Enables joining any channel and eavesdropping on voice/video.",
        "simulation": "Attacker joins a game voice channel, listens to private player communications.",
        "score_value": 20,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:M/A:N",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "General",
        "triage_note": "Rotate at console.agora.io. Enforce token auth — never use App ID alone in production.",
    },
    {
        "title": "AppLovin SDK Key",
        "regex": r"(?i)(applovin[_\-]?(sdk[_\-]?key|api[_\-]?key))\s*[=:]\s*['\"]([a-zA-Z0-9_\-]{40,})['\"]",
        "severity": "MEDIUM", "confidence": "HIGH", "exploitability": "LIKELY",
        "secret_type": "Ad Network Credential",
        "description": "AppLovin SDK key found. May allow ad fraud, bid manipulation, or revenue data exfiltration.",
        "simulation": "Attacker queries revenue data or generates fraudulent impressions.",
        "score_value": 10,
        "cvss_vector": "CVSS:3.1/AV:N/AC:M/PR:N/UI:N/S:U/C:M/I:M/A:N",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "General",
        "triage_note": "Rotate via AppLovin dashboard.",
    },
    {
        "title": "Xsolla Secret Key",
        "regex": r"(?i)(xsolla[_\-]?(merchant[_\-]?id|secret[_\-]?key|api[_\-]?key))\s*[=:]\s*['\"]([a-zA-Z0-9]{16,})['\"]",
        "severity": "CRITICAL", "confidence": "HIGH", "exploitability": "CONFIRMED",
        "secret_type": "Game Commerce Credential",
        "description": "Xsolla secret key found. Enables unauthorized purchase validation and player currency manipulation.",
        "simulation": "Attacker creates fraudulent orders or validates fake purchases.",
        "score_value": 35,
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        "cwe_id": "CWE-798", "owasp_ref": "M9: Insecure Data Storage", "category": "Economy",
        "triage_note": "Rotate at publisher.xsolla.com. Secret key must only exist server-side.",
    },
    {
        "title": "AES-ECB Mode Usage (Weak Cipher)",
        "regex": r'(?i)Cipher\.getInstance\([\'"]AES(/ECB|[\'"])',
        "severity": "MEDIUM", "confidence": "HIGH", "exploitability": "LIKELY",
        "secret_type": "Weak Cryptography",
        "description": "AES-ECB mode used or AES initialised without explicit mode. ECB leaks data patterns.",
        "simulation": "Attacker analyses ECB-encrypted blocks to deduce game state patterns.",
        "score_value": 10,
        "cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:M/I:N/A:N",
        "cwe_id": "CWE-327", "owasp_ref": "M5: Insufficient Cryptography", "category": "General",
        "triage_note": "Replace with AES/GCM/NoPadding or AES/CBC/PKCS5Padding with random IV.",
    },
    {
        "title": "Insecure Random Number Generator",
        "regex": r"(?i)(new\s+Random\(\)|Math\.random\(\)|java\.util\.Random)",
        "severity": "LOW", "confidence": "MEDIUM", "exploitability": "THEORETICAL",
        "secret_type": "Weak Cryptography",
        "description": "java.util.Random or Math.random() used in a security context — not cryptographically secure.",
        "simulation": "Attacker predicts token generation sequence or game seed.",
        "score_value": 5,
        "cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
        "cwe_id": "CWE-330", "owasp_ref": "M5: Insufficient Cryptography", "category": "General",
        "triage_note": "Use SecureRandom for any security-relevant randomness.",
    },
]
